### ISSUE TITLE
Scroll jumping when clicking on playlists

### ISSUE THREAD

**Issue by updxg** [jeroentvb/spicetify-playlist-icons#8] opened 2022-08-05 14:13 UTC
Whenever I click on a playlist, it randomly scroll jumps up, which is extremely annoying when trying to play a playlist from the sidebar, as in video related

https://user-images.githubusercontent.com/94653983/183094655-eb954cfd-9064-409d-bc33-66cf0e469c1c.mp4

Any idea why this might be?

**Comment by jeroentvb** [comment] 2022-08-05 16:13
I've never seen that happen before, and I use playlist icons on mac and windows on different spotify/spicetify versions.

Sadly if I can't reproduce it, I can't do anything about it.

**Comment by jeroentvb** [comment] 2022-08-09 06:28
I just had a look at it again. It might have to do with the big playlist icons. Spotify does some weird de-rendering when items are out of view, so those icons never worked as smooth as the small icons.

Can you try the small icons and see if the jumping is still an issue?

**Comment by updxg** [comment] 2022-08-09 08:17
Works fine with the small icons. 

Bizarre coding - why would they de-render minor things like the sidebar? That still doesn't fix their memory leak issues (which are bound to happen after just a few dozen searches in one session) so I don't see what's there to it.

**Comment by jeroentvb** [comment] 2022-08-09 08:34
I'm not sure either. It was the biggest challenge to overcome when making this extension, because the playlist icons get de-rendered as well, and I had to manually watch for changes and add them back when they spawned back in.

I just did manage to reproduce the jumping behaviour too with the large playlist icons. Will have to look into it, but I can't guarantee I can fix it. If it's too annoying you can use the small icons for now.

**Comment by jeroentvb** [comment] 2023-10-20 18:01
Closing this issue as these 'playlist list icons' are only rendered in legacy mode. Spotify now renders the icons themselves, so this shouldn't happen anymore.

**Closed as not planned by jeroentvb** 2023-10-20 18:01 UTC
Labels: bug
